/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  cognome: string;
  email: string;
  nome: string;
  password: string;
  username: string;
}
