spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

server:
  port: 8080
  servlet:
    context-path: /api/v1/

application:
  security:
    jwt:
      secret-key: SekXCnSydpc4aP9ol8AuTtMFMl8omHewz57Rf+JD8Xc=
      expiration: 8640000